
The only platform that fails wth boost 1.55 is AIX. vacpp 12.1


09:30:54 + /s2o1/emos_data/ecflow/boost/boost_1_55_0/bjam variant=debug -j2 -d2
link.jam: No such file or directory
...patience...
...patience...
...patience...
...patience...
...found 26749 targets...
...updating 20 targets...
vacpp.compile.c++ Base/bin/vacpp/debug/link-static/threading-multi/src/Client.o

    xlC_r -c -qsuppress=1540-0198 -qsuppress=1540-2883    -DAIX -DDEBUG -qcpluscmt -qNOOPTimize -qnoinline -g -qfullpath -qfuncsect -qeh -qrtti -I"/s2o1/emos_data/ecflow/boost/boost_1_55_0" -I"ACore/src" -I"ANattr/src" -I"ANode/src" -I"AParser/src" -I"Base/src" -I"Base/src/cts" -I"Base/src/stc"  -o "Base/bin/vacpp/debug/link-static/threading-multi/src/Client.o" "Base/src/Client.cpp"

"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 729.5: 1540-0218 (S) The call does not match any parameter list for "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >::operator()".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 172.10: 1540-1283 (I) "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >::operator()(const error_code &, std::size_t, int)" is not a viable candidate.
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 729.5: 1540-0215 (I) The wrong number of arguments has been specified for "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >::operator()(const erro...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 724.3: 1540-0700 (I) The previous message was produced while processing "boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::async_write_some<boost::asio::detail::consuming_buffers<boost::asio::const_buffer,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> > >,boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boos...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 181.18: 1540-0700 (I) The previous message was produced while processing "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >::operator()(const error_...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 624.50: 1540-0700 (I) The previous message was produced while processing "boost::asio::async_write<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >(basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_sock...".
"Base/src/Connection.hpp", line 151.17: 1540-0700 (I) The previous message was produced while processing "connection::async_write<ClientToServerRequest,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >(const ClientToServerRequest &, bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > >)".
"Base/src/Client.cpp", line 189.15: 1540-0700 (I) The previous message was produced while processing "Client::start_write()".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 842.5: 1540-0218 (S) The call does not match any parameter list for "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ServerToClientResponse &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_b...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 261.10: 1540-1283 (I) "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ServerToClientResponse &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::..." is not a viable candidate.
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 842.5: 1540-0215 (I) The wrong number of arguments has been specified for "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ServerToClientResponse &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boo...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 837.3: 1540-0700 (I) The previous message was produced while processing "boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::async_read_some<boost::asio::mutable_buffers_1,boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost:...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 271.18: 1540-0700 (I) The previous message was produced while processing "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ServerToClientResponse &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 561.50: 1540-0700 (I) The previous message was produced while processing "boost::asio::async_read<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ServerToClientResponse &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,...".
"Base/src/Connection.hpp", line 201.25: 1540-0700 (I) The previous message was produced while processing "connection::handle_read_header<ServerToClientResponse,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >(const error_code &, ServerToClientResponse &, tuple<boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > >,boost::tuples::null_type,bo...".
"Base/src/Connection.hpp", line 168.20: 1540-0700 (I) The previous message was produced while processing "connection::async_read<ServerToClientResponse,boost::_bi::bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > > >(ServerToClientResponse &, bind_t<void,boost::_mfi::mf1<void,Client,const boost::system::error_code &>,boost::_bi::list2<boost::_bi::value<Client *>,boost::arg<1> > >)".
"Base/src/Client.cpp", line 237.15: 1540-0700 (I) The previous message was produced while processing "Client::start_read()".
...failed vacpp.compile.c++ Base/bin/vacpp/debug/link-static/threading-multi/src/Client.o...
...skipped <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>src/Client.o...
...skipped <pBase/bin/vacpp/debug/threading-multi>basetest for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pClient/bin/vacpp/debug/threading-multi>ecflow_client for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pClient/bin/vacpp/debug/threading-multi>tclient for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pClient/bin/vacpp/debug/threading-multi>test_large_defs_perf for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pClient/bin/vacpp/debug/threading-multi>test_migration for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pCSim/bin/vacpp/debug/threading-multi>testsimulator for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pCSim/bin/vacpp/debug/threading-multi>testsingle for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pTest/bin/vacpp/debug/threading-multi>server-test for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pTest/bin/vacpp/debug/threading-multi>test-zombies for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
...skipped <pTest/bin/vacpp/debug/threading-multi>singletest for lack of <pBase/bin/vacpp/debug/link-static/threading-multi>libbase.a...
vacpp.compile.c++ Server/bin/vacpp/debug/link-static/threading-multi/src/Server.o

    xlC_r -c -qsuppress=1540-0198 -qsuppress=1540-2883    -DAIX -DDEBUG -qcpluscmt -qNOOPTimize -qnoinline -g -qfullpath -qfuncsect -qeh -qrtti -I"/s2o1/emos_data/ecflow/boost/boost_1_55_0" -I"ACore/src" -I"ANattr/src" -I"ANode/src" -I"AParser/src" -I"Base/src" -I"Base/src/cts" -I"Base/src/stc" -I"Server/src"  -o "Server/bin/vacpp/debug/link-static/threading-multi/src/Server.o" "Server/src/Server.cpp"

"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 842.5: 1540-0218 (S) The call does not match any parameter list for "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ClientToServerRequest &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shar...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 261.10: 1540-1283 (I) "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ClientToServerRequest &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,..." is not a viable candidate.
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 842.5: 1540-0215 (I) The wrong number of arguments has been specified for "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ClientToServerRequest &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 837.3: 1540-0700 (I) The previous message was produced while processing "boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::async_read_some<boost::asio::mutable_buffers_1,boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost:...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 271.18: 1540-0700 (I) The previous message was produced while processing "boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ClientToServerRequest &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/read.hpp", line 561.50: 1540-0700 (I) The previous message was produced while processing "boost::asio::async_read<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,boost::asio::mutable_buffers_1,boost::_bi::bind_t<void,boost::_mfi::mf3<void,connection,const boost::system::error_code &,ClientToServerRequest &,boost::tuples::tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list...".
"Base/src/Connection.hpp", line 201.25: 1540-0700 (I) The previous message was produced while processing "connection::handle_read_header<ClientToServerRequest,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boost::_bi::value<boost::shared_ptr<connection> > > > >(const error_code &, ClientToServerRequest &, tuple<boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared...".
"Base/src/Connection.hpp", line 168.20: 1540-0700 (I) The previous message was produced while processing "connection::async_read<ClientToServerRequest,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boost::_bi::value<boost::shared_ptr<connection> > > > >(ClientToServerRequest &, bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_b...".
"Server/src/Server.cpp", line 212.11: 1540-0700 (I) The previous message was produced while processing "Server::handle_accept(const error_code &, connection_ptr)".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 729.5: 1540-0218 (S) The call does not match any parameter list for "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boo...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 172.10: 1540-1283 (I) "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boost::_bi::value<boost:..." is not a viable candidate.
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 729.5: 1540-0215 (I) The wrong number of arguments has been specified for "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/basic_stream_socket.hpp", line 724.3: 1540-0700 (I) The previous message was produced while processing "boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >::async_write_some<boost::asio::detail::consuming_buffers<boost::asio::const_buffer,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> > >,boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boos...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 181.18: 1540-0700 (I) The previous message was produced while processing "boost::asio::detail::write_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::asio::detail::transfer_all_t,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>...".
"/s2o1/emos_data/ecflow/boost/boost_1_55_0/boost/asio/impl/write.hpp", line 624.50: 1540-0700 (I) The previous message was produced while processing "boost::asio::async_write<boost::asio::basic_stream_socket<boost::asio::ip::tcp,boost::asio::stream_socket_service<boost::asio::ip::tcp> >,std::vector<boost::asio::const_buffer,std::allocator<boost::asio::const_buffer> >,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boost::_bi::value<boost::shared_ptr<conn...".
"Base/src/Connection.hpp", line 151.17: 1540-0700 (I) The previous message was produced while processing "connection::async_write<ServerToClientResponse,boost::_bi::bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<boost::_bi::value<Server *>,boost::arg<1>,boost::_bi::value<boost::shared_ptr<connection> > > > >(const ServerToClientResponse &, bind_t<void,boost::_mfi::mf2<void,Server,const boost::system::error_code &,boost::shared_ptr<connection> >,boost::_bi::list3<...".
"Server/src/Server.cpp", line 269.11: 1540-0700 (I) The previous message was produced while processing "Server::handle_read(const error_code &, connection_ptr)".
...failed vacpp.compile.c++ Server/bin/vacpp/debug/link-static/threading-multi/src/Server.o...
...skipped <pServer/bin/vacpp/debug/link-static/threading-multi>libserver.a for lack of <pServer/bin/vacpp/debug/link-static/threading-multi>src/Server.o...
...skipped <pServer/bin/vacpp/debug/threading-multi>ecflow_server for lack of <pServer/bin/vacpp/debug/link-static/threading-multi>libserver.a...
...skipped <pServer/bin/vacpp/debug/threading-multi>tserver for lack of <pServer/bin/vacpp/debug/link-static/threading-multi>libserver.a...
vacpp.compile.c++ Pyext/bin/vacpp/debug/threading-multi/src/BoostPythonUtil.o

    xlC_r -c -qsuppress=1540-0198 -qsuppress=1540-2883    -DAIX -DDEBUG -qcpluscmt -qNOOPTimize -qnoinline -g -qfullpath -qfuncsect -qeh -qrtti -I"/s2o1/emos_data/ecflow/boost/boost_1_55_0" -I"/usr/local/apps/python/2.7.2-01/include/python2.7" -I"ACore/src" -I"ANattr/src" -I"ANode/src" -I"AParser/src" -I"Base/src" -I"Base/src/cts" -I"Base/src/stc" -I"CSim/src" -I"Client/src"  -o "Pyext/bin/vacpp/debug/threading-multi/src/BoostPythonUtil.o" "Pyext/src/BoostPythonUtil.cpp"

"/usr/local/apps/python/2.7.2-01/include/python2.7/pyconfig.h", line 1155.9: 1540-0848 (S) The macro name "_POSIX_C_SOURCE" is already defined with a different definition.
"/usr/include/standards.h", line 161.9: 1540-0425 (I) "_POSIX_C_SOURCE" is defined on line 161 of "/usr/include/standards.h".
"/usr/local/apps/python/2.7.2-01/include/python2.7/pyconfig.h", line 1177.9: 1540-0848 (S) The macro name "_XOPEN_SOURCE" is already defined with a different definition.
"/usr/include/standards.h", line 157.9: 1540-0425 (I) "_XOPEN_SOURCE" is defined on line 157 of "/usr/include/standards.h".
...failed vacpp.compile.c++ Pyext/bin/vacpp/debug/threading-multi/src/BoostPythonUtil.o...
...skipped <pPyext/bin/vacpp/debug/threading-multi>ecflow.so for lack of <pPyext/bin/vacpp/debug/threading-multi>src/BoostPythonUtil.o...
...skipped <pPyext/ecflow>ecflow.so for lack of <pPyext/bin/vacpp/debug/threading-multi>ecflow.so...
...failed updating 3 targets...
...skipped 17 targets...
09:32:05 + ERROR